[package]
name = "firma-vz-runner"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "Apple Virtualization runner for OpenFirma VZ launch contracts"

[[bin]]
name = "firma-vz-runner"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true, features = ["derive", "error-context", "help", "std", "usage"] }
ctrlc = { workspace = true }
firma-identifiers = { workspace = true }
firma-runtime-state = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
firma-fs = { workspace = true }
insta = { workspace = true }
tempfile = { workspace = true }

[target.'cfg(target_os = "macos")'.dependencies]
block2 = { workspace = true }
dispatch2 = { workspace = true }
libc = { workspace = true }
objc2 = { workspace = true }

[target.'cfg(target_os = "macos")'.dependencies.objc2-foundation]
workspace = true
features = [
  "NSArray",
  "NSDate",
  "NSDictionary",
  "NSError",
  "NSFileHandle",
  "NSObject",
  "NSRunLoop",
  "NSString",
  "NSURL",
]

# TODO we are using "dependencies.objc2-virtualization" instead of just objc2-virtualization = {}
# here just because dprint doesnt accept this kindof formatting.
# must be discussed to solve this later.
[target.'cfg(target_os = "macos")'.dependencies.objc2-virtualization]
workspace = true
features = [
  "VZBootLoader",
  "VZConsoleDeviceConfiguration",
  "VZConsolePortConfiguration",
  "VZDirectoryShare",
  "VZDirectorySharingDeviceConfiguration",
  "VZDiskImageStorageDeviceAttachment",
  "VZDiskSynchronizationMode",
  "VZEntropyDeviceConfiguration",
  "VZFileHandleSerialPortAttachment",
  "VZGenericMachineIdentifier",
  "VZGenericPlatformConfiguration",
  "VZLinuxBootLoader",
  "VZMultipleDirectoryShare",
  "VZPlatformConfiguration",
  "VZSerialPortAttachment",
  "VZSharedDirectory",
  "VZSocketDevice",
  "VZSocketDeviceConfiguration",
  "VZStorageDeviceAttachment",
  "VZStorageDeviceConfiguration",
  "VZVirtioBlockDeviceConfiguration",
  "VZVirtioConsoleDeviceConfiguration",
  "VZVirtioConsolePortConfiguration",
  "VZVirtioConsolePortConfigurationArray",
  "VZVirtioEntropyDeviceConfiguration",
  "VZVirtioFileSystemDeviceConfiguration",
  "VZVirtioSocketConnection",
  "VZVirtioSocketDevice",
  "VZVirtioSocketDeviceConfiguration",
  "VZVirtioSocketListener",
  "VZVirtualMachine",
  "VZVirtualMachineConfiguration",
  "block2",
  "dispatch2",
  "std",
]

[lints.clippy]
expect_used = "deny"
missing_const_for_fn = "allow"
nursery = { level = "warn", priority = -1 }
panic = "deny"
pedantic = { level = "deny", priority = -1 }
unwrap_used = "deny"

[lints.rust]
unsafe_code = "allow"
