[package]
name = "firma-identifiers"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
description = "Validated definitions, parsing, and generation for OpenFirma identifiers"

[lints]
workspace = true

[dependencies]
serde = { workspace = true }
thiserror = { workspace = true }
type-safe-id = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
insta = { workspace = true }
serde_json = { workspace = true }
