[package]
name = "firma"
version.workspace = true
edition.workspace = true
homepage = "https://openfirma.ai"
license.workspace = true
repository.workspace = true
description = "Firma CLI for managing and running OpenFirma components"

[package.metadata.dist]
changelog = "../../CHANGELOG.md"
dist = true

[[bin]]
name = "firma"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
cedar-policy = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true, features = ["color", "derive", "env", "error-context", "help", "std", "suggestions", "usage", "wrap_help"] }
ctrlc = { workspace = true }
dialoguer = { workspace = true }
firma-authority = { workspace = true }
firma-config-loader = { workspace = true, features = ["clap"] }
firma-core = { workspace = true }
firma-fs = { workspace = true }
firma-http = { workspace = true }
firma-run = { workspace = true }
firma-runtime-state = { workspace = true }
firma-sidecar = { workspace = true }
firma-stack = { workspace = true }
firma-tui = { workspace = true }
miette = { workspace = true }
owo-colors = { workspace = true }
p256 = { workspace = true }
pasetors = { workspace = true }
rcgen = { workspace = true }
same-file = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
sha2 = { workspace = true }
tempfile = { workspace = true }
thiserror = { workspace = true }
time = { workspace = true }
tokio = { workspace = true, default-features = false, features = ["fs", "macros", "net", "process", "rt-multi-thread", "signal", "sync", "time"] }
tokio-util = { workspace = true }
toml = { workspace = true }
toml_edit = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
uuid = { workspace = true }
x509-parser = { workspace = true }

[target.'cfg(unix)'.dependencies]
nix = { workspace = true }

[target.'cfg(windows)'.dependencies]
windows-sys = { workspace = true }

[dev-dependencies]
fs-err = { workspace = true }
guppy = "0.17"
http-body-util = { workspace = true }
hyper = { workspace = true, features = ["http1", "server"] }
hyper-util = { workspace = true, features = ["tokio"] }
insta = { workspace = true }
pretty_assertions = { workspace = true }
rand = { workspace = true }
regex = { workspace = true }
serde_repr = { workspace = true }
strum = { workspace = true, features = ["derive"] }
tempfile = { workspace = true }
wait-timeout = { workspace = true }
wiremock = { workspace = true }

[target.'cfg(unix)'.dev-dependencies]
nix = { workspace = true }

[[test]]
name = "e2e"
path = "../../tests/e2e/main.rs"

[[test]]
name = "architecture"
path = "../../tests/architecture/main.rs"
