[package]
name = "firma"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Firma CLI for managing and running OpenFirma components"
license.workspace = true
repository.workspace = true

[[bin]]
name = "firma"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
cedar-policy = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true, features = [
  "color",
  "derive",
  "env",
  "error-context",
  "help",
  "std",
  "suggestions",
  "usage",
] }
ctrlc = { workspace = true }
firma-authority = { workspace = true }
firma-config = { workspace = true }
firma-core = { workspace = true }
firma-run = { workspace = true }
firma-sidecar = { workspace = true }
firma-stack = { workspace = true }
miette = { workspace = true }
pasetors = { workspace = true }
rcgen = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
tempfile = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, default-features = false, features = [
  "fs",
  "macros",
  "net",
  "process",
  "rt-multi-thread",
  "signal",
  "sync",
  "time",
] }
tokio-util = { workspace = true }
toml = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[target.'cfg(unix)'.dependencies]
nix = { workspace = true }

[target.'cfg(windows)'.dependencies]
windows-sys = { workspace = true }

[dev-dependencies]
p256 = { workspace = true }
pretty_assertions = { workspace = true }
rand = { workspace = true }
tempfile = { workspace = true }

[target.'cfg(unix)'.dev-dependencies]
nix = { workspace = true }
