#!/usr/bin/env bash
# Snapshot the runtime shared-library dependencies of the released
# `opensidecar` binary. Run on every reference host; commit the
# updated `docs/release/binary-deps.md` so reviewers can see drift.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BIN="$ROOT/target/release/opensidecar"
OUT="$ROOT/docs/release/binary-deps.md"

if [[ ! -x "$BIN" ]]; then
  echo "[snapshot] missing $BIN — run 'cargo build --release -p opensidecar' first" >&2
  exit 1
fi

mkdir -p "$(dirname "$OUT")"

uname_s="$(uname -s)"
case "$uname_s" in
  Darwin)
    tool="otool -L"
    deps="$(otool -L "$BIN" | tail -n +2 | awk '{print $1}')"
    ;;
  Linux)
    tool="ldd"
    deps="$(ldd "$BIN" | awk '{print $1}')"
    ;;
  *)
    echo "[snapshot] unsupported platform '$uname_s'" >&2
    exit 1
    ;;
esac

{
  echo "# opensidecar release binary dependency snapshot"
  echo
  echo "Generated by \`scripts/snapshot-binary-deps.sh\`. Re-run on every"
  echo "release host and commit any diff so reviewers can see drift."
  echo
  echo "- Host: \`$uname_s\` ($(uname -m))"
  echo "- Tool: \`$tool\`"
  echo "- Binary: \`$BIN\`"
  echo "- Captured: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo
  echo '```text'
  echo "$deps"
  echo '```'
} > "$OUT"

echo "[snapshot] wrote $OUT"
