set shell := ["bash", "-eu", "-o", "pipefail", "-c"]

dir := justfile_directory()

default: policy-control

policy-control:
  @bash "{{dir}}/demo.sh" run

start:
  @bash "{{dir}}/demo.sh" start

control:
  @bash "{{dir}}/demo.sh" control

agent target="operations":
  @cd "{{dir}}" && PYTHONDONTWRITEBYTECODE=1 python3 -m agent "{{target}}" --interval 0

stop:
  @bash "{{dir}}/demo.sh" stop
