[package]
name = "firma-demo-tui"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "firma-demo-tui"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
ansi-to-tui = "8"
anyhow.workspace = true
clap = { workspace = true, features = ["color", "derive", "error-context", "help", "std", "suggestions", "usage"] }
crossterm = "0.28"
firma-config-loader = { workspace = true }
firma-runtime-state = { workspace = true }
firma-stack = { workspace = true }
ratatui = "0.30"
serde.workspace = true
serde_json.workspace = true
toml.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
tui-markdown = "0.3.7"
