[package]
name = "firma-sidecar"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "HTTP proxy sidecar with enforcement pipeline for Firma OSS"
license.workspace = true
repository.workspace = true

[dependencies]
chrono = { workspace = true }
firma-core = { path = "../firma-core" }
firma-proto = { path = "../firma-proto" }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
toml = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true, default-features = false, features = [
  "rt-multi-thread",
  "net",
] }
tokio-util = { workspace = true }
tracing-subscriber = { workspace = true }

[lints]
workspace = true
