name: Bench

on:
  workflow_dispatch:

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  bench:
    name: Bench
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false

      - uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2

      - name: Install protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Bench
        run: cargo bench --workspace --no-fail-fast -- --quick

      - name: Upload criterion reports
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: criterion-reports
          path: target/criterion/**
          if-no-files-found: warn
          retention-days: 14
